# Generated by Django 4.2.6 on 2023-11-07 21:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_loan_dni_loan_email_loan_first_name_loan_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='dni',
            field=models.IntegerField(db_index=True, unique=True, validators=[django.core.validators.RegexValidator(message='El DNI debe contener 8 dígitos numéricos.', regex='^\\d{8}$')]),
        ),
        migrations.AlterField(
            model_name='loan',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='loan',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='loan',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1),
        ),
        migrations.AlterField(
            model_name='loan',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='loan',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.IntegerField(choices=[(0, 'En espera'), (1, 'Aceptado'), (2, 'Rechazado'), (3, 'Error')]),
        ),
    ]
